#NDI SDK Build Details
#Mon Sep 28 15:05:30 GMT 2026
date=12\:51\:52 Apr 13 2026
path=/home/nprodanov/Documents/Projects/ffmpeg-test/opensong-extensions/distributions/ndi-library/build/lib/libndi.so
platform=LINUX
version=6.3.2.0
